### PR TITLE
Refactor Test and Example

### PR DESCRIPTION
**Pull request by codenio**
This PR,
- Refactors `progress_test.go` to unit test progress pkg. As mentioned in the official golang [testing](https://golang.org/pkg/testing/) package.
-  moves `example_test.go` into ./example for making it an independent code.

### CODE REVIEW

**Review by sfreiberg — COMMENTED** [review]
Can you explain where you see these go standards? A search of the strings library for example shows things exactly as they currently are not as you propose. Also I don't see tremendous value in the change to be honest as it works as is and is at least consistent with one of the core go libraries.

**Comment by codenio** [comment]
I felt these could be improved
- A directory is supposed to have a single package. We have progress and progress_test in the same dir. Refernce from From [How to write go code](https://golang.org/doc/code.html#PackagePaths)
> Each package consists of one or more Go source files in a single directory.
- Unit testing is in general done on the same package. Reference from [Testing](https://golang.org/pkg/testing/)
> To write a new test suite, create a file whose name ends _test.go that contains the functions as described here. Put the file in the same package as the one being tested.
- example.go being independent become handy to have the quickstart.

**Comment by sfreiberg** [comment]
So I see where it says that but that differs from the std library. There are reasons to do it both ways and both ways are clearly fine. This feels very pedantic and unless there's a technical reason to change (testing an unexported func for example) I'm not inclined to accept the PR. Even if I were I do not want the example in a separate directory. It's the way it is so it's included appropriately in the godocs.

**Comment by codenio** [comment]
@sfreiberg thanks for the detailed explanation 👍

**Pull request closed without merging**
